import {Plus_Jakarta_Sans } from "next/font/google";
import "./style/tailwind.css";
import "@/public/icon/iconly.css";

const plusjakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Foodking - Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${plusjakarta.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
