import {Plus_Jakarta_Sans } from "next/font/google";
import "./style/tailwind.css";
import "@/public/icon/iconly.css";

import ReduxProvider from "@/redux/store/ReduxProvider";

const plusjakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Foodking - Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${plusjakarta.variable} antialiased`}>
        <ReduxProvider>
            {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
